{
 "title": "Carbon-relay-ng",
 "description": "visualize Carbon-relay-ng's metrics",
 "tags": [ "telemetry" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_*"
   },
   {
    "name": "dest",
    "query": "stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.dest_is_*"
   }
  ]
 },
 "panels": [
  {
   "title": "$instance incoming",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.unit_is_Metric.*), 4)"
    },
    {
     "target": "alias(perSecond(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.unit_is_Err.type_is_invalid), 'invalid')"
    },
    {
     "target": "alias(perSecond(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.unit_is_Err.type_is_out_of_order), 'out-of-order')"
    }
   ]
  },
  {
   "title": "dest metric directions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.dest_is_$dest.unit_is_Metric.direction_is_out), 'to tcp')"
    },
    {
     "target": "alias(perSecond(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.spool_is_$dest.unit_is_Metric.status_is_incomingRT), 'to spool')"
    }
   ]
  },
  {
   "title": "dest metric drops",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.dest_is_$dest.unit_is_Metric.action_is_drop.*),6)"
    }
   ]
  },
  {
   "title": "dest Errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.dest_is_$dest.unit_is_Err.*), 5)"
    }
   ]
  },
  {
   "title": "conn Flush size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_ticker.stat_is_max, 'ticker max')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_ticker.stat_is_max_99, 'ticker 99')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_ticker.stat_is_mean,'ticker mean')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_manual.stat_is_max, 'manual max')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_manual.stat_is_max_99, 'manual 99')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_manual.stat_is_mean, 'manual mean')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_overflow.stat_is_max,'overflow max')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_overflow.stat_is_max99, 'overflow 99')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_overflow.mean,\"overflow mean\")"
    }
   ]
  },
  {
   "title": "conn metrics in buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_Metric.what_is_numBuffered, 'numBuffered')"
    }
   ]
  },
  {
   "title": "conn flush durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.dest_is_$dest.what_is_durationFlush.type_is_ticker.stat_is_max, '\"ticker max\"')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.dest_is_$dest.what_is_durationFlush.type_is_ticker.stat_is_mean, '\"ticker mean\"')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.dest_is_$dest.what_is_durationFlush.type_is_overflow.stat_is_max, '\"overflow max\"')"
    },
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.dest_is_$dest.what_is_durationFlush.type_is_overflow.stat_is_mean, '\"overflow mean\"')"
    }
   ]
  },
  {
   "title": "spool inputs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_carbonrelay1-next.mtype_is_counter.spool_is_$dest.unit_is_Metric.*, 5)"
    },
    {}
   ]
  },
  {
   "title": "spool metrics in buffer",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_carbonrelay1-next.mtype_is_gauge.spool_is_$dest.unit_is_Metric.status_is_buffered, 'buffered')"
    }
   ]
  },
  {
   "title": "spool durations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_carbonrelay1-next.mtype_is_gauge.unit_is_ns.spool_is_$dest.operation_is*.stat_is_max_50, 5, 6)"
    },
    {
     "target": "aliasByNode(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_carbonrelay1-next.mtype_is_gauge.unit_is_ns.spool_is_$dest.operation_is*.stat_is_max_95, 5, 6)"
    },
    {
     "target": "aliasByNode(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_carbonrelay1-next.mtype_is_gauge.unit_is_ns.spool_is_$dest.operation_is*.stat_is_max, 5, 6)"
    },
    {
     "target": "aliasByNode(stats.carbon-relay-ng.service_is_carbon-relay-ng.instance_is_carbonrelay1-next.mtype_is_gauge.unit_is_ns.spool_is_$dest.operation_is*.stat_is_mean, 5, 6)"
    }
   ]
  }
 ]
}