{
 "title": "Carbonapi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByMetric(sumSeries(stats.carbonapi.agents.*.cache_size))"
    }
   ]
  },
  {
   "title": "Cache items",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "aliasByMetric(sumSeries(stats.carbonapi.agents.*.cache_items))"
    }
   ]
  },
  {
   "title": "Find requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "aliasByMetric(sumSeries(stats.carbonapi.agents.*.find_requests))"
    }
   ]
  },
  {
   "title": "Render requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "aliasByMetric(sumSeries(stats.carbonapi.agents.*.render_requests))"
    }
   ]
  }
 ]
}