{
 "title": "Go-Carbon",
 "tags": [ "telemetry" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "agent", "label": "Carbon Agent", "query": "stats.gocarbon.agents.*" }
  ]
 },
 "panels": [
  {
   "title": "Metric Inputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.tcp.metricsReceived), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.udp.metricsReceived), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.pickle.metricsReceived), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.*.errors), 4)"
    }
   ]
  },
  {
   "title": "Persister Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.persister.updateOperations), 'Updates')"
    },
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.persister.committedPoints), 'Committed Points')"
    },
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.persister.created), 'Creates')"
    },
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.persister.pointsPerUpdate), 'Points per Update')"
    }
   ]
  },
  {
   "title": "Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.cache.size), 4)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.cache.queries), 4)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.cache.maxSize), 4)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.cache.overflow), 4)"
    }
   ]
  },
  {
   "title": "Queue Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.cache.queueWriteoutTime), 'Queue Writeout Time')"
    },
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.cache.queueBuildTimeMs), 'Queue Build Time')"
    },
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.cache.queueBuildCount), 'Queue Rebuilds')"
    }
   ]
  },
  {
   "title": "Comitted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.*.persister.committedPoints), 'Commited', false)"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.*.persister.updateOperations), 'Updates', false)"
    }
   ]
  },
  {
   "title": "Created files",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.*.persister.created), 'Commited', false)"
    }
   ]
  },
  {
   "title": "Throttled new files",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gocarbon.agents.*.persister.throttledCreates)"
    }
   ]
  }
 ]
}