{
 "title": "Admin Utils Server Stats",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Users",
    "query": "screeps.adminUtilsServerStats.users.*"
   },
   {
    "name": "Team_A",
    "query": "{Gadjung,Modus,slowmotionghost,PacifistBot,Kalgen,Trepidimous,SBense}"
   },
   {
    "name": "Team_B",
    "query": "{V1king,Saruss,Mirroar,Yoner,asdpof,Silten,MarvinTMB}"
   },
   { "name": "Avg", "query": "1m,5m,30m,1h,6h,1d,7d" }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Game time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.adminUtilsServerStats.gametime"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.adminUtilsServerStats.activeUsers"
    }
   ]
  },
  {
   "title": "Owned rooms",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.adminUtilsServerStats.ownedRooms"
    }
   ]
  },
  {
   "title": "Active rooms",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.adminUtilsServerStats.activeRooms"
    }
   ]
  },
  {
   "title": "Total objects",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "diffSeries(screeps.adminUtilsServerStats.objects.all, #B)",
     "targetFull": "diffSeries(screeps.adminUtilsServerStats.objects.all, screeps.adminUtilsServerStats.objects.creeps)"
    }
   ]
  },
  {
   "title": "Total creeps",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.adminUtilsServerStats.objects.creeps"
    }
   ]
  },
  {
   "title": "Tick speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "aliasByMetric(screeps.adminUtilsServerStats.ticks.avg)"
    },
    {
     "target": "aliasByMetric(screeps.adminUtilsServerStats.ticks.max)"
    },
    {
     "target": "aliasByMetric(screeps.adminUtilsServerStats.ticks.min)"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GCL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(screeps.adminUtilsServerStats.users.$Users.gcl), 3)"
    }
   ]
  },
  {
   "title": "GCL level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(screeps.adminUtilsServerStats.users.$Users.gclLevel), 3)"
    }
   ]
  },
  {
   "title": "GCL per tick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(divideSeries(perSecond(screeps.adminUtilsServerStats.users.$Users.gcl), #B)), 3)",
     "targetFull": "aliasByNode(removeEmptySeries(divideSeries(perSecond(screeps.adminUtilsServerStats.users.$Users.gcl), perSecond(screeps.adminUtilsServerStats.gametime))), 3)"
    }
   ]
  },
  {
   "title": "GCL per second (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(movingAverage(perSecond(screeps.adminUtilsServerStats.users.$Users.gcl), '$Avg')), 3)"
    }
   ]
  },
  {
   "title": "Combined RCL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(screeps.adminUtilsServerStats.users.$Users.combinedRCL), 3)"
    }
   ]
  },
  {
   "title": "Creeps (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(movingAverage(screeps.adminUtilsServerStats.users.$Users.creeps, '$Avg')), 3)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(screeps.adminUtilsServerStats.users.$Users.cpu), 3)"
    }
   ]
  },
  {
   "title": "GPL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(screeps.adminUtilsServerStats.users.$Users.powerLevel), 3)"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(screeps.adminUtilsServerStats.users.$Users.power), 3)"
    }
   ]
  },
  { "title": "Teams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "GCL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "target": "alias(sum(screeps.adminUtilsServerStats.users.$Team_A.gcl), 'Team A', false)"
    },
    {
     "target": "alias(sum(screeps.adminUtilsServerStats.users.$Team_B.gcl), 'Team B', false)"
    }
   ]
  },
  {
   "title": "GCL Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "target": "alias(sum(screeps.adminUtilsServerStats.users.$Team_A.gclLevel), 'Team A', false)"
    },
    {
     "target": "alias(sum(screeps.adminUtilsServerStats.users.$Team_B.gclLevel), 'Team B', false)"
    }
   ]
  },
  {
   "title": "GCL per tick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "target": "alias(removeEmptySeries(sum(divideSeries(perSecond(screeps.adminUtilsServerStats.users.$Team_A.gcl), #C))), 'Team A', false)",
     "targetFull": "alias(removeEmptySeries(sum(divideSeries(perSecond(screeps.adminUtilsServerStats.users.$Team_A.gcl), perSecond(screeps.adminUtilsServerStats.gametime)))), 'Team A', false)"
    },
    {
     "target": "alias(removeEmptySeries(sum(divideSeries(perSecond(screeps.adminUtilsServerStats.users.$Team_B.gcl), #C))), 'Team B', false)",
     "targetFull": "alias(removeEmptySeries(sum(divideSeries(perSecond(screeps.adminUtilsServerStats.users.$Team_B.gcl), perSecond(screeps.adminUtilsServerStats.gametime)))), 'Team B', false)"
    }
   ]
  },
  {
   "title": "Creeps (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "target": "alias(movingAverage(sum(screeps.adminUtilsServerStats.users.$Team_A.creeps), '$Avg'), 'Team A', false)"
    },
    {
     "target": "alias(movingAverage(sum(screeps.adminUtilsServerStats.users.$Team_B.creeps), '$Avg'), 'Team B', false)"
    }
   ]
  },
  {
   "title": "Combined RCL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "target": "alias(sum(screeps.adminUtilsServerStats.users.$Team_A.combinedRCL), 'Team A', false)"
    },
    {
     "target": "alias(sum(screeps.adminUtilsServerStats.users.$Team_B.combinedRCL), 'Team B', false)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "target": "alias(sum(screeps.adminUtilsServerStats.users.$Team_A.cpu), 'Team A', false)"
    },
    {
     "target": "alias(sum(screeps.adminUtilsServerStats.users.$Team_B.cpu), 'Team B', false)"
    }
   ]
  }
 ]
}