{
 "title": "Server stats",
 "time": { "from": "2023-02-17T00:29:52.437Z", "to": "2023-02-21T09:23:24.239Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Users",
    "query": {}
   },
   {
    "name": "Rooms",
    "query": {}
   },
   { "name": "Moving_average", "query": "1minute, 1hour, 4hour, 1day" }
  ]
 },
 "panels": [
  {
   "title": "Tick speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByMetric(screeps.adminUtilsServerStats.ticks.max)"
    },
    {
     "target": "aliasByMetric(screeps.adminUtilsServerStats.ticks.avg)"
    },
    {
     "target": "aliasByMetric(screeps.adminUtilsServerStats.ticks.min)"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Rooms count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "aliasByNode(screeps.serverStats.users.$Users.roomsCount, 3)"
    }
   ]
  },
  {
   "title": "GCL per tick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(divideSeriesLists(perSecond(screeps.serverStats.users.$Users.gcl), #B), '$Moving_average'), 3)",
     "targetFull": "aliasByNode(movingAverage(divideSeriesLists(perSecond(screeps.serverStats.users.$Users.gcl), perSecond(screeps.serverStats.gameTime)), '$Moving_average'), 3)"
    }
   ]
  },
  {
   "title": "GCL expected timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "target": "movingAverage(divideSeries(diffSeries(screeps.serverStats.users.$Users.overview.gcl.progressTotal, #B), #A), '1hour')",
     "targetFull": "movingAverage(divideSeries(diffSeries(screeps.serverStats.users.$Users.overview.gcl.progressTotal, screeps.serverStats.users.$Users.overview.gcl.progress), perSecond(screeps.serverStats.users.$Users.overview.gcl.progress)), '1hour')"
    }
   ]
  },
  {
   "title": "CPU used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "aliasByNode(divideSeriesLists(screeps.serverStats.users.$Users.lastUsedCpu, #B), 3)",
     "targetFull": "aliasByNode(divideSeriesLists(screeps.serverStats.users.$Users.lastUsedCpu, screeps.serverStats.users.$Users.cpu), 3)"
    }
   ]
  },
  {
   "title": "Combined rcl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "target": "aliasByNode(screeps.serverStats.users.$Users.overview.combinedRCL, 3)"
    }
   ]
  },
  {
   "title": "Structures count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "groupByNode(screeps.serverStats.users.$Users.overview.structureCounts.*, 3, 'sumSeries')"
    }
   ]
  },
  {
   "title": "Creeps count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "target": "aliasByNode(screeps.serverStats.users.$Users.overview.creepCount, 3)"
    }
   ]
  },
  {
   "title": "Construction sites count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "aliasByNode(screeps.serverStats.users.$Users.overview.constructionSitesCount, 3)"
    }
   ]
  },
  {
   "title": "Dropped energy count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "target": "aliasByNode(screeps.serverStats.users.$Users.overview.droppedEnergyTotal, 3)"
    }
   ]
  }
 ]
}