{
 "title": "Stats",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "Users", "query": "stats.*" },
   { "name": "Shards", "query": "stats.$Users.*" },
   { "name": "Rooms", "query": "stats.$Users.$Shards.rooms.*" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cpu used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(stats.$Users.$Shards.cpu.usage), 1)"
    },
    {
     "target": "aliasByNode(stats.$Users.$Shards.cpu.limit, 1, 3, 4)"
    }
   ]
  },
  {
   "title": "Energy Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(movingAverage(groupByNode(stats.$Users.$Shards.rooms.$Rooms.eih, 5, 'sum'), 60), 'Harvest')"
    },
    {
     "target": "alias(movingAverage(groupByNode(stats.$Users.$Shards.rooms.$Rooms.eob, 5, 'sum'), 60), 'Build')"
    },
    {
     "target": "alias(movingAverage(groupByNode(stats.$Users.$Shards.rooms.$Rooms.eoro, 5, 'sum'), 60), 'Repair Other')"
    },
    {
     "target": "alias(movingAverage(groupByNode(stats.$Users.$Shards.rooms.$Rooms.eorwr, 5, 'sum'), 60), 'Repair Barricades')"
    },
    {
     "target": "alias(movingAverage(groupByNode(stats.$Users.$Shards.rooms.$Rooms.eosp, 5, 'sum'), 60), 'Spawning')"
    },
    {
     "target": "alias(movingAverage(groupByNode(stats.$Users.$Shards.rooms.$Rooms.reih, 5, 'sum'), 60), 'Remote Harvest')"
    },
    {
     "target": "alias(movingAverage(removeZeroSeries(groupByNode(stats.$Users.$Shards.rooms.$Rooms.reob, 5, 'sum')), 60), 'Remote Build')"
    },
    {
     "target": "alias(movingAverage(removeZeroSeries(groupByNode(stats.$Users.$Shards.rooms.$Rooms.reoro, 5, 'sum')), 60), 'Remote Repair Other')"
    },
    {
     "target": "alias(movingAverage(groupByNode(stats.$Users.$Shards.rooms.$Rooms.eou, 5, 'sum'), 60), 'Upgrading')"
    },
    {
     "target": "alias(movingAverage(removeZeroSeries(groupByNode(stats.$Users.$Shards.rooms.$Rooms.eib, 5, 'sum')), 60), 'Bought')"
    },
    {
     "target": "alias(movingAverage(removeZeroSeries(groupByNode(stats.$Users.$Shards.rooms.$Rooms.eos, 5, 'sum')), 60), 'Sold')"
    }
   ]
  },
  {
   "title": "Global Control Level",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(stats.$Users.$Shards.gcl.level, 1))"
    }
   ]
  },
  {
   "title": "Global Power Level",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(stats.$Users.$Shards.gpl.level, 1))"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(divideSeriesLists(stats.$Users.$Shards.cpu.usage, #B)), 1)",
     "targetFull": "aliasByNode(removeZeroSeries(divideSeriesLists(stats.$Users.$Shards.cpu.usage, stats.$Users.$Shards.cpu.limit)), 1)"
    }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(divideSeriesLists(stats.$Users.$Shards.gcl.progress, #B)), 1)",
     "targetFull": "aliasByNode(removeZeroSeries(divideSeriesLists(stats.$Users.$Shards.gcl.progress, stats.$Users.$Shards.gcl.progressTotal)), 1)"
    }
   ]
  },
  {
   "title": "GPL Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(divideSeriesLists(stats.$Users.$Shards.gpl.progress, #B)), 1)",
     "targetFull": "aliasByNode(removeZeroSeries(divideSeriesLists(stats.$Users.$Shards.gpl.progress, stats.$Users.$Shards.gpl.progressTotal)), 1)"
    }
   ]
  },
  {
   "title": "Cpu bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.cpu.bucket, 50)), 1)"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(stats.$Users.$Shards.resources.credits), 1)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(divideSeriesLists(stats.$Users.$Shards.memory.usage, #B)), 1)",
     "targetFull": "aliasByNode(removeZeroSeries(divideSeriesLists(stats.$Users.$Shards.memory.usage, stats.$Users.$Shards.memory.limit)), 1)"
    }
   ]
  },
  {
   "title": "Construction site count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.constructionSiteCount, 1)"
    }
   ]
  },
  {
   "title": "Leaderboard Rank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(stats.$Users.$Shards.leaderboard.rank), 1)"
    }
   ]
  },
  {
   "title": "Last Global reset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(stats.$Users.$Shards.lastReset), 1)"
    }
   ]
  },
  {
   "title": "Tick duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "groupByNode(removeAboveValue(stats.$Users.$Shards.tickLength, 100000), 2, 'averageSeries')"
    }
   ]
  },
  {
   "title": "Pixels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(stats.$Users.$Shards.resources.pixels), 1)"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Creep count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "refCount": -1,
     "target": "groupByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.tcc, 5)), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy stored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "target": "groupByNode(movingAverage(group(removeZeroSeries(stats.$Users.$Shards.rooms.$Rooms.res), #A), 5), 1, 'sum')",
     "targetFull": "groupByNode(movingAverage(group(removeZeroSeries(stats.$Users.$Shards.rooms.$Rooms.res), removeZeroSeries(stats.$Users.$Shards.rooms.$Rooms.es)), 5), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy Net income",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "refCount": 1,
     "target": "groupByNode(diffSeriesLists(#M, #I), 0, 'sum')",
     "targetFull": "groupByNode(diffSeriesLists(groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eih, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reih, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eib, 5))), 1, 'sum'), groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eou, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eoro, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eorwr, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eob, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eos, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eosp, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reoro, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reob, 5))), 1, 'sum')), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Energy Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "target": "groupByNode(group(#A, #B, #C), 1, 'sum')",
     "targetFull": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eih, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reih, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eib, 5))), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Spawn Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "groupByNode(movingAverage(stats.$Users.$Shards.rooms.$Rooms.su, 5), 1, 'averageSeries')"
    }
   ]
  },
  {
   "title": "Energy Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "target": "groupByNode(group(#A, #B, #C, #D, #E, #F, #G, #H), 1, 'sum')",
     "targetFull": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eou, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eoro, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eorwr, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eob, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eos, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eosp, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reoro, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reob, 5))), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy input - Harvest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "target": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eih, 5)), #B), 1, 'sum')",
     "targetFull": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eih, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reih, 5))), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy input - Bought",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "target": "groupByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eib, 5)), 1, 'sum')",
     "targetFull": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eib, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reih, 5))), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy output - Upgrade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "target": "groupByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eou, 5)), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy output - Spawn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "target": "groupByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eosp, 5)), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy output - Repair",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "target": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eorwr, 5)), #A, #B), 1, 'sum')",
     "targetFull": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eorwr, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eoro, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reoro, 5))), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy output - Build",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "target": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reob, 5)), #A), 1, 'sum')",
     "targetFull": "groupByNode(group(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reob, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eob, 5))), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Energy output - Sold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "target": "groupByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eos, 5)), 1, 'sum')"
    }
   ]
  },
  {
   "title": "Commune Rooms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.cu, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Creep count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.cc, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Controller level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(stats.$Users.$Shards.rooms.$Rooms.cl), 1, 4)"
      }
     ]
    },
    {
     "title": "Spawn Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.su, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy stored",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(stats.$Users.$Shards.rooms.$Rooms.es), 1, 4)"
      }
     ]
    },
    {
     "title": "Minerals harvested",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "target": "removeZeroSeries(aliasByNode(stats.$Users.$Shards.rooms.$Rooms.mh, 1, 4))"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote Rooms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "refCount": -1,
       "target": "aliasByNode(stats.$Users.$Shards.rooms.$Rooms.rc, 1, 4)"
      }
     ]
    },
    {
     "title": "Cpu used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.rcu, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Creep count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "target": "aliasByNode(diffSeriesLists(#A, #B), 1, 4)",
       "targetFull": "aliasByNode(diffSeriesLists(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.tcc, 5)), removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.cc, 5))), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy stored",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(stats.$Users.$Shards.rooms.$Rooms.res), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy input - Harvest",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reih, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy output - Build",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reob, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy output - Repair Other",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.reoro, 5)), 1, 4)"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Commune",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy input - Harvest",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eih, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy output - TOTAL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "target": "groupByNodes(removeZeroSeries(movingAverage(group(#A, #B, #C, #D, #E), 5)), 'sum', 0, 1)",
       "targetFull": "groupByNodes(removeZeroSeries(movingAverage(group(aliasByNode(stats.$Users.$Shards.rooms.$Rooms.eob, 1, 4), aliasByNode(stats.$Users.$Shards.rooms.$Rooms.eoro, 1, 4), aliasByNode(stats.$Users.$Shards.rooms.$Rooms.eoso, 1, 4), aliasByNode(stats.$Users.$Shards.rooms.$Rooms.eoro, 1, 4), aliasByNode(stats.$Users.$Shards.rooms.$Rooms.eosp, 1, 4)), 5)), 'sum', 0, 1)"
      }
     ]
    },
    {
     "title": "Energy output - Build",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eob, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy output - Spawn",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eosp, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy output - Upgrade",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eou, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy output - Repair Wall/Rampart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eorwr, 5)), 1, 4)"
      }
     ]
    },
    {
     "title": "Energy output - Repair Other",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$Rooms.eoro, 5)), 1, 4)"
      }
     ]
    }
   ]
  }
 ]
}